export const GET_TWEETS_LIST_SUCCESS = 'GET_TWEETS_LIST_SUCCESS';
export const GET_TWEETS_LIST_FAIL = 'GET_TWEETS_LIST_FAIL';
export const POST_TWEET_SUCCESS = 'POST_TWEET_SUCCESS'
export const POST_TWEET_FAIL = 'POST_TWEET_FAIL'